export type IconsType =
  | "pen"
  | "hamburger"
  | "home"
  | "scale"
  | "calculator"
  | "payment"
  | "customer"
  | "employee"
  | "arrow-down"
  | "filter-arrow-up"
  | "filter-arrow-down"
  | "filter-arrow-up-down"
  | "search"
  | "print"
  | "export";
